---

- name: Ensure packages are installed
  apt:  name="{{ item }}" state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items: "{{ wkhtmltox_packages }}"
  tags: [wkhtmltox, packages]
  
- name: Ensure download directory exists
  file: state=directory path="{{ wkhtmltox_download_dir }}" owner=root group=root mode=0755
  tags: [wkhtmltox, dirs]
  
- name: Ensure prefix directory exists
  file: state=directory path="{{ wkhtmltox_prefix_dir }}" owner=root group=root mode=0755
  tags: [wkhtmltox, dirs]

- name: Ensure release is downloaded
  get_url:
    url:  "{{ wkhtmltox_release_url }}"
    dest: "{{ wkhtmltox_download_dir }}/wkhtmltox-{{ wkhtmltox_version }}_{{ wkhtmltox_arch }}.tar"
    mode: 0640
  register: new_wkhtmltox_release
  tags: [wkhtmltox, release]

- name: Extract release
  when: new_wkhtmltox_release | changed
  unarchive:
    src: "{{ wkhtmltox_download_dir }}/wkhtmltox-{{ wkhtmltox_version }}_{{ wkhtmltox_arch }}.tar"
    dest: "{{ wkhtmltox_prefix_dir }}"
    remote_src: True
  tags: [wkhtmltox, release]

- name: Ensure wkhtmltopdf binary is symlinked
  file: state=link src="{{ wkhtmltox_prefix_dir }}/wkhtmltox/bin/wkhtmltopdf" dest="{{ wkhtmltox_bin_dir }}/wkhtmltopdf" mode=0755
  tags: [wkhtmltox, link]
